<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>syncmodspro</AssemblyName>
    <RootNamespace>Calloatti.SyncModsPro</RootNamespace>
    <TimberbornPath>C:\Program Files (x86)\Steam\steamapps\common\timberborn_public\Timberborn_Data\Managed</TimberbornPath>
  </PropertyGroup>

  <Import Project="CommonModSettings.props" />

  <ItemGroup>
    <None Update="Data\save_metadata.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Data\save_thumbnail.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Data\version.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Data\world.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="rosetta.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>


